### PR TITLE
Change sorting to move inactive leaderboards behind active ones

### PR DESCRIPTION
**Pull request by jdunn596**
This change will move inactive leaderboards to the end of the leaderboards list.

Sorting will first be by active state, then by number of races, and finally by name.

### CODE REVIEW

**Comment by jdunn596** [comment]
I also had an idea for the `annotate` method to filter races that are older than 30 days but I have no real way to test to see it actually works (I would assume not as I have very little experience with django). All I can say is that it doesn't crash the app but I'm not sure if it actually does anything 😆 

```python
goals = goals.annotate(
    num_races=db_models.Count(
        'race__id',
         filter=[race for race in self.past_races() if race['ended_at'] > timezone.now().date() - timedelta(days=30)]
    )
)
```

**Comment by deains** [comment]
> I also had an idea for the `annotate` method to filter races that are older than 30 days but I have no real way to test to see it actually works (I would assume not as I have very little experience with django). All I can say is that it doesn't crash the app but I'm not sure if it actually does anything 😆
> 
> ```python
> goals = goals.annotate(
>     num_races=db_models.Count(
>         'race__id',
>          filter=[race for race in self.past_races() if race['ended_at'] < timezone.now().date() - timedelta(days=30)]
>     )
> )
> ```

This probably isn't a good idea as a fixed time limit like this would not be appropriate for all categories. Only the heavily raced ones would want something like this, take a category like the Mario 602 for example, which gets raced like clockwork exactly once every 6 months, a limit like this would prevent the counter ever going above zero.

**Review by deains — APPROVED** [review]

**Comment by deains** [comment]
I'll aim to get this live at a quiet point next week :)

**Comment by jdunn596** [comment]
Sweet thanks Dyn!

**Pull request merged**
