### PR TITLE
Modify pronouns options to include more gender non-binary opotions

### LINKED ISSUE #124: Additional Pronoun options
Racetime currently has three options for pronouns on the site - masculine (he/him), feminine (she/her), and neutral (they/them). While this is good, it doesn't cover everything. Would it be possible to add more options for people who do not identify as one of those three, or multiple.

For example:
1) other pronouns (Ze/Zir, Ze/Hir, Xe/Xem, Fae/Faer etc)
2) she/they and he/they for those who identify as a mix of neutral and feminine/masculine.
3) The option of Any for those who do not have a preference

### PR DESCRIPTION
**Pull request by nihonjinrxs**
Closes #124

This PR adds more gender non-binary options for personal pronouns. It also adds an `any` option for folks who have no preference and removes the unnecessary "descriptive" text for the pronoun selections, which likely does more harm than good in a non-binary context.

Screenshots below.

screenshot-pronouns-selection

screenshot-pronouns-userprofile

screenshot-pronouns-in-race

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
Per discussion in #124, I've updated this to only include the existing options, plus a new "other/ask!" option.

Screen Shot 2021-08-01 at 10 20 26 PM

Screen Shot 2021-08-01 at 10 19 41 PM

Screen Shot 2021-08-01 at 10 18 39 PM

**Review by deains — CHANGES_REQUESTED** [review]
You've rolled this back further than I expected. 😛 I think we should go ahead with some of the original changes:
* Removing the "feminine/masculine/neutral" descriptors as they aren't really any use
* she/they and he/they I think should remain in the list

Let's remove `verbose_name` as well, so the field is just called "Pronouns". From what I've read, "preferred pronouns" is probably a bit outdated.

And don't forget that this is a model change, so it will need a migration added. 🙂

**Comment by nihonjinrxs** [comment]
Sorry, I've had some medical stuff I've been dealing with, so I've been a bit busy. I haven't forgotten about this, and will get to it sometime this weekend. 😅

**Comment by nihonjinrxs** [comment]
I believe this last commit handles the changes as directed, and also adds the requisite migration. Let me know if there are further changes to make. Thanks!

Screen Shot 2021-08-15 at 1 28 49 PM

**Comment by nihonjinrxs** [comment]
@deains Appreciate another look at this one when you have a minute. Thanks!

**Review by deains — APPROVED** [review]
Approved, thanks for your patience!

**Pull request merged**
